### ISSUE TITLE
ply file is not displayed on the screen.

### ISSUE THREAD

**Issue by TejNote** [dbrant/ModelViewer3D#19]
[test_ply.zip](https://github.com/dbrant/ModelViewer3D/files/10801711/full_part_refined.ply.zip)

hello.
I tried to open a ply file using the good library you made, but the ply file I have is not displayed on the screen.

It's a binary file, and I checked that the data was normally imported through readVerticesBinary, but it wasn't actually displayed on the screen.

could i get some help?

**Comment by dbrant** [comment]
I've just updated the PLY code to improve support for differently-formatted files. Please try again with the updated code.

The PLY support is still rather limited, simply because I don't have access to a whole lot of different PLY files to compare, so thanks for sending this example file.

(Note that this file will still load as a point-cloud instead of a true mesh (that's tracked in #10), but at least it should load.)

**Comment by dbrant** [comment]
Update: I have now updated the code so that it properly loads PLY files as a mesh instead of point cloud. Let me know if you have any other PLY files that don't render correctly in the app!

**Comment by TejNote** [comment]
Thank you very much.
We will make good use of a good library.
